# Generated by Django 5.1.1 on 2024-10-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Articulos',
        ),
    ]
